language: ruby
rvm:
  - "1.9.3"
before_script:
  - psql -c 'create database billingly_test;' -U postgres
  - "bundle exec rake db:test:prepare db:migrate RAILS_ENV=test" 
script: "bundle exec rspec spec"
